INHERIT: ./common/mkdocs_base.yml

site_name: k8s
# site_description: sasano8's portfolio
# site_url: https://portfolio.ys-method.com/
repo_url: https://github.com/sasano8/k8s_sample
edit_uri: "edit/main/docs/"

nav:
  - はじめに: "index.md"

